
package Presentacion;

import Entidad.clsEDetalleServicio;
import Negocio.*;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.HashMap;
import java.util.Map;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


public class EditarDetalleServicio extends javax.swing.JFrame {

    DefaultTableModel modeloDetalleServicio;
    DefaultTableModel modeloArticulo;
    Map<Integer, String> mapServicios = new HashMap<>();
    public EditarDetalleServicio() {
        initComponents();
        modeloDetalleServicio = new DefaultTableModel();
        modeloDetalleServicio.addColumn("ID");
        modeloDetalleServicio.addColumn("ID SERVICIO");
        modeloDetalleServicio.addColumn("ARTICULO");
        modeloDetalleServicio.addColumn("CANTIDAD");
        modeloDetalleServicio.addColumn("NOMBRE");
        tblDetalleServicio.setModel(modeloDetalleServicio);
        listarDetalleServicio();

        cmbServicio.setModel(new DefaultComboBoxModel<>());
        llenarComboBox();
        
        // Agregar ActionListener al JComboBox cmbServicio
        cmbServicio.addActionListener((e) -> {
            String descripcionSeleccionada = (String) cmbServicio.getSelectedItem();
            for (Map.Entry<Integer, String> entry : mapServicios.entrySet()) {
                if (entry.getValue().equals(descripcionSeleccionada)) {
                    txtIdServicio.setText(String.valueOf(entry.getKey()));
                    break;
                }
            }
        });

        modeloArticulo = new DefaultTableModel();
        modeloArticulo.addColumn("ID");
        modeloArticulo.addColumn("NOMBRE");
        modeloArticulo.addColumn("DESCRIPCION");
        modeloArticulo.addColumn("PRECIO C/U");
        tblArticulo.setModel(modeloArticulo);
        listarArticulos();
    }
    
    private void listarArticulos(){
        mtdLimpiarTabla(modeloArticulo);
        clsNDetalleServicio objNDS = new clsNDetalleServicio();
        ResultSet rs = objNDS.mtdListaArticulos();
        try {
            while (rs.next()) {
                String dato[] = new String[4];
                dato[0] = rs.getString("id_articulo");
                dato[1] = rs.getString("nombre");
                dato[2] = rs.getString("descripcion");
                dato[3] = rs.getString("precio_unitario");
                modeloArticulo.addRow(dato);
            }
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
        tblArticulo.setModel(modeloArticulo);
    }
    
    private void llenarComboBox() {
        clsNDetalleServicio objNDS = new clsNDetalleServicio();
        ResultSet rs = objNDS.obtenerServicios();
        try {
            cmbServicio.removeAllItems(); // Limpiar items previos
            mapServicios.clear(); // Limpiar mapa previo
            while (rs.next()) {
                int idServicio = rs.getInt("id_servicio");
                String descripcion = rs.getString("descripcion");
                cmbServicio.addItem(descripcion);
                mapServicios.put(idServicio, descripcion);
            }
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
    }
    
    private void listarDetalleServicio(){
        mtdLimpiarTabla(modeloDetalleServicio);
        clsNDetalleServicio objNE = new clsNDetalleServicio();
        ResultSet rs = objNE.mtdListarDetalleServicio();
        try {
            while (rs.next()) {
                String dato[] = new String[5];
                dato[0] = rs.getString("id_detalle_servicio");
                dato[1] = rs.getString("id_servicio");
                dato[2] = rs.getString("id_articulo");
                dato[3] = rs.getString("cantidad");
                dato[4] = rs.getString("descripcion");
                modeloDetalleServicio.addRow(dato);
            }
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
        tblDetalleServicio.setModel(modeloDetalleServicio);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtIdDetalleServicio = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtIdServicio = new javax.swing.JTextField();
        cmbServicio = new javax.swing.JComboBox<>();
        txtIdArticulo = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtCantidad = new javax.swing.JTextField();
        btnEditar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDetalleServicio = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblArticulo = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btncerrar = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setFont(new java.awt.Font("Yu Gothic", 1, 14)); // NOI18N
        jLabel3.setText("ID Detalla Servicio:");

        txtIdDetalleServicio.setEditable(false);

        jLabel2.setFont(new java.awt.Font("Yu Gothic", 1, 14)); // NOI18N
        jLabel2.setText("ID Servicio:");

        txtIdServicio.setEditable(false);

        cmbServicio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        txtIdArticulo.setEditable(false);

        jLabel4.setFont(new java.awt.Font("Yu Gothic", 1, 14)); // NOI18N
        jLabel4.setText("ID Articulo:");

        jLabel5.setFont(new java.awt.Font("Yu Gothic", 1, 14)); // NOI18N
        jLabel5.setText("Cantidad de uso:");

        btnEditar.setBackground(new java.awt.Color(58, 96, 125));
        btnEditar.setFont(new java.awt.Font("Yu Gothic", 1, 18)); // NOI18N
        btnEditar.setForeground(new java.awt.Color(255, 255, 255));
        btnEditar.setText("Editar");
        btnEditar.setMargin(new java.awt.Insets(10, 14, 3, 14));
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        tblDetalleServicio.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblDetalleServicio.setGridColor(new java.awt.Color(58, 96, 125));
        tblDetalleServicio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDetalleServicioMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblDetalleServicio);

        tblArticulo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblArticulo.setGridColor(new java.awt.Color(58, 96, 125));
        tblArticulo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblArticuloMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblArticulo);

        jPanel2.setBackground(new java.awt.Color(58, 96, 125));

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Editar articulos de un Servicio");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(272, 272, 272)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );

        btncerrar.setBackground(new java.awt.Color(58, 96, 125));
        btncerrar.setFont(new java.awt.Font("Myanmar Text", 1, 14)); // NOI18N
        btncerrar.setForeground(new java.awt.Color(58, 96, 125));
        btncerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/back.png"))); // NOI18N
        btncerrar.setText("REGRESAR AL MENU");
        btncerrar.setToolTipText("");
        btncerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btncerrarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btncerrarMouseEntered(evt);
            }
        });

        jLabel9.setBackground(new java.awt.Color(58, 96, 125));
        jLabel9.setFont(new java.awt.Font("Yu Gothic", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(58, 96, 125));
        jLabel9.setText("Lista de Servicios :");

        jLabel10.setBackground(new java.awt.Color(58, 96, 125));
        jLabel10.setFont(new java.awt.Font("Yu Gothic", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(58, 96, 125));
        jLabel10.setText("Lista de Articulos");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel4)
                        .addComponent(jLabel5)
                        .addComponent(jLabel2)
                        .addComponent(txtIdDetalleServicio)
                        .addComponent(jLabel3)
                        .addComponent(txtIdArticulo, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnEditar, javax.swing.GroupLayout.DEFAULT_SIZE, 231, Short.MAX_VALUE)
                        .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtIdServicio, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbServicio, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btncerrar)
                        .addGap(40, 40, 40))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 559, Short.MAX_VALUE)
                                .addComponent(jScrollPane2)))
                        .addGap(0, 44, Short.MAX_VALUE))))
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel9))
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtIdDetalleServicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtIdServicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbServicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtIdArticulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41)
                        .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btncerrar)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.LINE_START);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tblArticuloMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblArticuloMouseClicked
        int fila =tblArticulo.getSelectedRow();
        txtIdArticulo.setText((String)tblArticulo.getValueAt(fila,0));
    }//GEN-LAST:event_tblArticuloMouseClicked

    private void tblDetalleServicioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDetalleServicioMouseClicked
        int fila =tblDetalleServicio.getSelectedRow();
        txtIdDetalleServicio.setText((String)tblDetalleServicio.getValueAt(fila,0));
        txtIdServicio.setText((String)tblDetalleServicio.getValueAt(fila,1));
        txtIdArticulo.setText((String)tblDetalleServicio.getValueAt(fila,2));
        txtCantidad.setText((String)tblDetalleServicio.getValueAt(fila,3));
    }//GEN-LAST:event_tblDetalleServicioMouseClicked

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
    clsEDetalleServicio objEDS = new clsEDetalleServicio();
    clsNDetalleServicio objNDS = new clsNDetalleServicio();

    // Obtener los valores de los campos de texto
    int idDetalleServicio = Integer.parseInt(txtIdDetalleServicio.getText());
    int idServicio = Integer.parseInt(txtIdServicio.getText());
    int idArticulo = Integer.parseInt(txtIdArticulo.getText());

    // Verificar que el campo de cantidad (txtCantidad) no esté vacío antes de convertirlo a entero
    String cantidadTexto = txtCantidad.getText().trim();
    if (cantidadTexto.isEmpty()) {
        JOptionPane.showMessageDialog(null, "Por favor, ingresa una cantidad válida.", "Campo Vacío", JOptionPane.WARNING_MESSAGE);
        return; // Salir del método si el campo está vacío
    }

    // Verificar que el valor ingresado sea un número entero positivo o cero
    int cantidadUso;
    try {
        cantidadUso = Integer.parseInt(cantidadTexto);
        if (cantidadUso < 0) {
            JOptionPane.showMessageDialog(null, "Por favor, ingresa una cantidad mayor o igual a 0.", "Valor Inválido", JOptionPane.WARNING_MESSAGE);
            return; // Salir del método si el valor es negativo
        }
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(null, "Por favor, ingresa un número entero válido.", "Valor Inválido", JOptionPane.WARNING_MESSAGE);
        return; // Salir del método si no se pudo convertir a entero
    }

    // Setear los atributos en el objeto clsEDetalleServicio
    objEDS.setId_detalle_servicio(idDetalleServicio);
    objEDS.setId_servicio(idServicio);
    objEDS.setId_articulo(idArticulo);
    objEDS.setCantidad(cantidadUso);

    // Llamar al método de edición y mostrar mensaje según el resultado
    if (objNDS.mtdEditarDetalleServicio(objEDS)) {
        JOptionPane.showMessageDialog(null, "Se editó el detalle de servicio correctamente");
        listarDetalleServicio();  // Actualizar la tabla después de editar
    } else {
        JOptionPane.showMessageDialog(null, "Error al guardar el detalle de servicio");
    }
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btncerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btncerrarMouseClicked

        FrmMenuServicios frm = new FrmMenuServicios();
        frm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btncerrarMouseClicked

    private void btncerrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btncerrarMouseEntered

    }//GEN-LAST:event_btncerrarMouseEntered

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditarDetalleServicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditarDetalleServicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditarDetalleServicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditarDetalleServicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditarDetalleServicio().setVisible(true);
            }
        });
    }

    private void mtdLimpiarTabla(DefaultTableModel model) {
        int filas = model.getRowCount();
        for (int i = 0; i < filas; i++) {
            model.removeRow(0);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEditar;
    private javax.swing.JLabel btncerrar;
    private javax.swing.JComboBox<String> cmbServicio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblArticulo;
    private javax.swing.JTable tblDetalleServicio;
    private javax.swing.JTextField txtCantidad;
    private javax.swing.JTextField txtIdArticulo;
    private javax.swing.JTextField txtIdDetalleServicio;
    private javax.swing.JTextField txtIdServicio;
    // End of variables declaration//GEN-END:variables
}
