/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Presentacion;


import Negocio.clsReportes;

public class FrmMenuReporte extends javax.swing.JFrame {

    /**
     * Creates new form FrmMenuReporte
     */
    public FrmMenuReporte() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnreporte1 = new javax.swing.JButton();
        btnreporte2 = new javax.swing.JButton();
        btnreporte3 = new javax.swing.JButton();
        btnreporte4 = new javax.swing.JButton();
        btncerrar = new javax.swing.JLabel();
        btnreporte5 = new javax.swing.JButton();
        btnreporte7 = new javax.swing.JButton();
        btnreporte8 = new javax.swing.JButton();
        txtAño = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(58, 96, 125));

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Menu Reporte");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(298, 298, 298)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        btnreporte1.setBackground(new java.awt.Color(58, 96, 125));
        btnreporte1.setFont(new java.awt.Font("Yu Gothic", 1, 18)); // NOI18N
        btnreporte1.setForeground(new java.awt.Color(255, 255, 255));
        btnreporte1.setText("Reservas al Año");
        btnreporte1.setMargin(new java.awt.Insets(10, 14, 3, 14));
        btnreporte1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnreporte1ActionPerformed(evt);
            }
        });

        btnreporte2.setBackground(new java.awt.Color(58, 96, 125));
        btnreporte2.setFont(new java.awt.Font("Yu Gothic", 1, 18)); // NOI18N
        btnreporte2.setForeground(new java.awt.Color(255, 255, 255));
        btnreporte2.setText("Cantidad de Perros");
        btnreporte2.setMargin(new java.awt.Insets(10, 14, 3, 14));
        btnreporte2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnreporte2ActionPerformed(evt);
            }
        });

        btnreporte3.setBackground(new java.awt.Color(58, 96, 125));
        btnreporte3.setFont(new java.awt.Font("Yu Gothic", 1, 18)); // NOI18N
        btnreporte3.setForeground(new java.awt.Color(255, 255, 255));
        btnreporte3.setText("Ganancias al Mes");
        btnreporte3.setMargin(new java.awt.Insets(10, 14, 3, 14));
        btnreporte3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnreporte3ActionPerformed(evt);
            }
        });

        btnreporte4.setBackground(new java.awt.Color(58, 96, 125));
        btnreporte4.setFont(new java.awt.Font("Yu Gothic", 1, 18)); // NOI18N
        btnreporte4.setForeground(new java.awt.Color(255, 255, 255));
        btnreporte4.setText("Ganancias Por Dia");
        btnreporte4.setMargin(new java.awt.Insets(10, 14, 3, 14));
        btnreporte4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnreporte4ActionPerformed(evt);
            }
        });

        btncerrar.setBackground(new java.awt.Color(58, 96, 125));
        btncerrar.setFont(new java.awt.Font("Myanmar Text", 1, 14)); // NOI18N
        btncerrar.setForeground(new java.awt.Color(58, 96, 125));
        btncerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/back.png"))); // NOI18N
        btncerrar.setText("REGRESAR AL MENU");
        btncerrar.setToolTipText("");
        btncerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btncerrarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btncerrarMouseEntered(evt);
            }
        });

        btnreporte5.setBackground(new java.awt.Color(58, 96, 125));
        btnreporte5.setFont(new java.awt.Font("Yu Gothic", 1, 18)); // NOI18N
        btnreporte5.setForeground(new java.awt.Color(255, 255, 255));
        btnreporte5.setText("Perros por Tamaño");
        btnreporte5.setMargin(new java.awt.Insets(10, 14, 3, 14));
        btnreporte5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnreporte5ActionPerformed(evt);
            }
        });

        btnreporte7.setBackground(new java.awt.Color(58, 96, 125));
        btnreporte7.setFont(new java.awt.Font("Yu Gothic", 1, 18)); // NOI18N
        btnreporte7.setForeground(new java.awt.Color(255, 255, 255));
        btnreporte7.setText("Servicio Popular");
        btnreporte7.setMargin(new java.awt.Insets(10, 14, 3, 14));
        btnreporte7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnreporte7ActionPerformed(evt);
            }
        });

        btnreporte8.setBackground(new java.awt.Color(58, 96, 125));
        btnreporte8.setFont(new java.awt.Font("Yu Gothic", 1, 18)); // NOI18N
        btnreporte8.setForeground(new java.awt.Color(255, 255, 255));
        btnreporte8.setText("Ganancias Por Año");
        btnreporte8.setMargin(new java.awt.Insets(10, 14, 3, 14));
        btnreporte8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnreporte8ActionPerformed(evt);
            }
        });

        jLabel9.setBackground(new java.awt.Color(58, 96, 125));
        jLabel9.setFont(new java.awt.Font("Yu Gothic", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(58, 96, 125));
        jLabel9.setText("Seleccione el año para ver las ganancias:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(161, 161, 161)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnreporte2, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnreporte1, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnreporte5, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnreporte3, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtAño, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnreporte7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnreporte8, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(btnreporte4, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(87, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btncerrar)
                .addGap(30, 30, 30))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnreporte1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnreporte2, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnreporte5, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btnreporte8, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnreporte7, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnreporte4, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtAño, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnreporte3, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(btncerrar)
                .addGap(27, 27, 27))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnreporte1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnreporte1ActionPerformed
        
    clsReportes reportes = new clsReportes();
    reportes.ReporteCanPorAÑO();
    }//GEN-LAST:event_btnreporte1ActionPerformed

    private void btnreporte2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnreporte2ActionPerformed
    clsReportes reportes = new clsReportes();
    reportes.CantidadPerros();         // TODO add your handling code here:
    }//GEN-LAST:event_btnreporte2ActionPerformed

    private void btnreporte3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnreporte3ActionPerformed
    String año = txtAño.getText().trim();   
    clsReportes reportes = new clsReportes();
    reportes.GananciaPorMes(año);         // TODO add your handling code here:
    }//GEN-LAST:event_btnreporte3ActionPerformed

    private void btnreporte4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnreporte4ActionPerformed
    clsReportes reportes = new clsReportes();
    reportes.CantidadPorDia();        // TODO add your handling code here:
    }//GEN-LAST:event_btnreporte4ActionPerformed

    private void btncerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btncerrarMouseClicked

        FrmPrincipal frm = new FrmPrincipal();
        frm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btncerrarMouseClicked

    private void btncerrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btncerrarMouseEntered

    }//GEN-LAST:event_btncerrarMouseEntered

    private void btnreporte5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnreporte5ActionPerformed
        clsReportes reportes = new clsReportes();
        reportes.PerrosPorTamaño();        // TODO add your handling code here:
    }//GEN-LAST:event_btnreporte5ActionPerformed

    private void btnreporte7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnreporte7ActionPerformed
        clsReportes reportes = new clsReportes();
        reportes.ServicioMasPopular();        
    }//GEN-LAST:event_btnreporte7ActionPerformed

    private void btnreporte8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnreporte8ActionPerformed
    clsReportes reportes = new clsReportes();
    reportes.GananciaPorAño();        // TODO add your handling code here:
    }//GEN-LAST:event_btnreporte8ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmMenuReporte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmMenuReporte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmMenuReporte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmMenuReporte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmMenuReporte().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btncerrar;
    private javax.swing.JButton btnreporte1;
    private javax.swing.JButton btnreporte2;
    private javax.swing.JButton btnreporte3;
    private javax.swing.JButton btnreporte4;
    private javax.swing.JButton btnreporte5;
    private javax.swing.JButton btnreporte7;
    private javax.swing.JButton btnreporte8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField txtAño;
    // End of variables declaration//GEN-END:variables
}
